"""
Django settings for plataforma_cursos project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Diretório RAIZ
BASE_DIR = Path(__file__).resolve().parent.parent

# KEY que nunca pode ser exibida
SECRET_KEY = 'django-insecure-is4jo=y4w80gi8km1ho&tiim^$7n*wwr2v)746bh91jzy)-vel'

# DEBUG = False # --> Quando for hospedar
DEBUG = True # --> Quando estiver em produção
# DEBUG --> Ajudar com informações de erros e soluções

ALLOWED_HOSTS = []

# Apps instalados
INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth', 
  'django.contrib.contenttypes', 
  'django.contrib.sessions', 
  'django.contrib.messages', 
  'django.contrib.staticfiles',
  # python3 manage.py startapp usuarios 
  'usuarios',
  # python3 manage.py makemigrations
  # python3 manage.py migrate
  'cursos',
  ]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware', 
  'django.contrib.sessions.middleware.SessionMiddleware', 
  'django.middleware.common.CommonMiddleware', 
  'django.middleware.csrf.CsrfViewMiddleware', 
  'django.contrib.auth.middleware.AuthenticationMiddleware', 
  'django.contrib.messages.middleware.MessageMiddleware', 
  'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'plataforma_cursos.urls'

TEMPLATES = [{
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  # Diretórios com templates de HTML
  'DIRS': [os.path.join(BASE_DIR, "templates")],
  'APP_DIRS': True,
  'OPTIONS': {
    'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']
  }
}]

WSGI_APPLICATION = 'plataforma_cursos.wsgi.application'

# Conectar com o banco de dados
DATABASES = {
  'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3'
  }
}

AUTH_PASSWORD_VALIDATORS = [{
  'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
}, {
  'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'
}, {
  'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
}, {
  'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
}]

LANGUAGE_CODE = 'pt-BR' # Idioma
TIME_ZONE = 'America/Sao_Paulo' # TimeZone
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = os.path.join(BASE_DIR, "templates/static"),
STATIC_ROOT = os.path.join("static")

# Pasta onde as imagens serão postadas
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
